// This file is generated by build:icons;
  
export const iconNames = [
  "cloud-download-outline",
  "dashed-circle",
  "facebook",
  "folder-outline",
  "home-outline",
  "loading-outline",
  "search-outline",
  "user-outline"
] as const;

export type IconNames = (typeof iconNames)[number];
