// This file is generated by build:icons;

export const iconNames = [
  'check',
  'chevron-right',
  'circle',
  'cloud-download-outline',
  'copy-check',
  'copy',
  'dashed-circle',
  'facebook',
  'folder-outline',
  'home-outline',
  'loading-outline',
  'moon',
  'search-outline',
  'sun',
  'user-outline',
] as const;

export type IconNames = (typeof iconNames)[number];
