name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup yarn
        run: npm install -g yarn


      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: corepack enable
      - run: yarn install
      - run: yarn lint && yarn build
